### PR TITLE
fix for #30 with unit test

### PR DESCRIPTION
**Pull request by PDoakORNL**
see #30 
python -m unittest python_params_test.py

try this.  worked for 2.7 and 3.6.5 for me.

### CODE REVIEW

**Comment by biddisco** [comment]
I don't know what this means ...
```
jb-s76:~/src/pycicle (issue_30 %<>)$ python -m unittest ./python_params_test.py
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.6/unittest/__main__.py", line 18, in <module>
    main(module=None)
  File "/usr/lib/python3.6/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/usr/lib/python3.6/unittest/main.py", line 141, in parseArgs
    self.createTests()
  File "/usr/lib/python3.6/unittest/main.py", line 148, in createTests
    self.module)
  File "/usr/lib/python3.6/unittest/loader.py", line 219, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib/python3.6/unittest/loader.py", line 219, in <listcomp>
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib/python3.6/unittest/loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
ValueError: Empty module name
```

**Comment by biddisco** [comment]
ok. I was trying to be too clever. This runs
```
jb-s76:~/src/pycicle (issue_30 %<>)$ python -m unittest python_params_test.py
E
======================================================================
ERROR: python_params_test (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: python_params_test
Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
ModuleNotFoundError: No module named 'python_params_test'


----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
```

**Comment by biddisco** [comment]
```
jb-s76:~/src/pycicle (master %<>)$ pip freeze
arandr==0.1.9
certifi==2018.4.16
chardet==3.0.4
coinmarketcap==4.2.1
idna==2.6
louis==3.5.0
mercurial==4.6
netsnmp-python==1.0a1
numpy==1.14.3
psutil==5.4.5
pwquality==1.4.0
pycairo==1.17.0
PyGithub==1.39
pygobject==3.28.2
PyJWT==1.6.1
python-libtorrent==1.1.7
requests==2.18.4
requests-cache==0.4.13
team==1.0
terminator==1.91
urllib3==1.22
```
```
jb-s76:~/src/pycicle (master %<>)$ pip3 freeze
appdirs==1.4.3
backcall==0.1.0
backports.weakref==1.0rc1
bleach==2.1.3
chardet==3.0.4
clingkernel==0.0.2
coinmarketcap==4.2.1
cupshelpers==1.0
cycler==0.10.0
decorator==4.3.0
docopt==0.6.2
entrypoints==0.2.3
gevent==1.2.2
greenlet==0.4.13
html5lib==1.0.1
idna==2.6
ipykernel==4.6.1
ipython==6.3.1
ipython-genutils==0.1.0
ipywidgets==6.0.0
jedi==0.12.0
Jinja2==2.10
jsonschema==2.6.0
jupyter-client==5.2.2
jupyter-console==5.2.0
jupyter-core==4.4.0
keyutils==0.5
lensfun==0.3.2
louis==3.5.0
Markdown==2.6.8
MarkupSafe==1.0
matplotlib==2.0.0
mistune==0.8.1
nbconvert==5.3.1
nbformat==4.4.0
notebook==5.3.0
npyscreen==4.10.5
numpy==1.14.3
olefile==0.45.1
packaging==17.1
pacman-mirrors==4.10.1
pandas==0.20.3
pandas-datareader==0.5.0
pandocfilters==1.4.2
parso==0.2.0
pexpect==4.5.0
pickleshare==0.7.4
Pillow==5.1.0
prompt-toolkit==1.0.15
protobuf==3.4.0
ptyprocess==0.5.2
pycairo==1.17.0
pycups==1.9.73
pycurl==7.43.0.1
PyGithub==1.40a1
Pygments==2.2.0
pygobject==3.28.2
PyJWT==1.5.3
pyparsing==2.2.0
pysmbc==1.0.15.8
python-dateutil==2.7.3
python-libtorrent==1.1.7
pytz==2017.2
PyYAML==3.12
pyzmq==16.0.3
reportlab==3.4.0
requests==2.18.4
requests-cache==0.4.13
requests-file==1.4.2
requests-ftp==0.3.1
scipy==1.0.0
Send2Trash==1.5.0
simplegeneric==0.8.1
simplejson==3.11.1
six==1.11.0
team==1.0
tensorflow==1.2.1
tensorflow-gpu==1.2.1
terminado==0.8.1
testpath==0.3.1
tornado==4.5.3
traitlets==4.3.2
udiskie==1.7.3
urllib3==1.22
wcwidth==0.1.7
webencodings==0.5.1
websocket==0.2.1
Werkzeug==0.12.2
widgetsnbextension==2.0.0
yahoo-finance==1.4.0
youtube-dl==2017.5.9
```
```
python --version
Python 3.6.5
```

**Comment by PDoakORNL** [comment]
The behavior of explicitly importing unittest seems to vary.

what does
```
python pycicle_params_test.py
```
produce?

**Comment by biddisco** [comment]
```
jb-s76:~/src/pycicle (issue_30 %<>)$ python pycicle_params_test.py
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
```
Seems legit

**Comment by PDoakORNL** [comment]
This should be ready to merge then. For now this is the easiest way to have some tests without making pycicle into an actual package.

**Comment by biddisco** [comment]
Problem solved. I did not actually check the original command line that you pasted.
if I run 
`python -m unittest pycicle_params_test.py`
instead of 
`python -m unittest python_params_test.py`
then it works fine.

Apologies for being useless.

**Pull request merged**
