### PR TITLE
Dca access control

### PR DESCRIPTION
**Pull request by PDoakORNL**
Wish this was broken up better. 

This PR Adds:
* out of pycicle config, you can put the configuration in your project or anywhere you want.
* basic access control, only organization members in the case of an org owned repo or users with push permission for a user owned repo have their PR's built. So randoms can not build arbitrary code wherever you are running pycicle.
* update of dca config to work with this pycicle. (soon it will be moved to the DCA repo and removed from here)

I think I have preserved the legacy behavior so existing pycicle projects will not need to update their configs.

### CODE REVIEW

**Comment by PDoakORNL** [comment]
Addresses #14
example use
```shell
python pycicle/pycicle.py -a -m cadesGPUCondo -P dca --config-path=/lustre/or-hydra/cades-cnms/epd/DCA_PUBLIC_GPU_CI/pycicle/config/dca -t ${TOKEN%\\n} -r `pwd`
```

**Comment by biddisco** [comment]
Is there a way to say `--config-path` in the repo that the PR is coming from, so for the case of DCA, I want to test the hpx branch and I put the pycicle build config with the HPX info needed in some place like `dca/build/config/...`
I have not looked at the code yet, but hopefully/maybe you will see this before I spend too long on it

**Comment by PDoakORNL** [comment]
Yes I have some way to do that, but I won’t have time to look until late today.  I can document this evening.
Sadly it was long enough ago that I did it and its not running right now that I  will have to do a bit of exploration.
Its even possible something hasn’t gotten pushed. :(

**Comment by biddisco** [comment]
ok, there's no great hurry, but what I had in mind was to completely bypass the local config stuff and say something like
```
python pycicle.py -g https://github.com/CompFUSE/DCA --config-path=@project@/tools/pycicle/dca.cmake [-p 167] ... blah blah blah
```
so that we pass the repo and the relative path to the config setup (and if the branch being tested happens to override settings, then they can be picked up too)

Also : Do you think it's safe to merge this. I can't see anything wrong - it's just that I have some old branches I'd like to work on and I might as well rebase them onto this work - however, if you remember that something is not right, do say so and I'll hold off merging to master.

**Comment by biddisco** [comment]
I've added a couple of extra commits to this branch that fixed a few issues for me. I'm going to merge it because I would like to use this as the base for some more PR's I have coming.

**Comment by PDoakORNL** [comment]
Sorry I've been unresponsive on this, slammed on other project. Thanks for fixing and merging!

**Comment by biddisco** [comment]
Be careful if you try master - I think I commit a few mistakes in my haste - I'll fix more and put them into my next PR

**Pull request merged**
