### PR TITLE
Cades config

### PR DESCRIPTION
**Pull request by PDoakORNL**
Changes to get pycicle to work on Cades Condo system.  Among them making the transport local instead of ssh when that is appropriate.

### CODE REVIEW

**Comment by PDoakORNL** [comment]
Also fixed calls to system find which bombed on Centos7.

**Comment by biddisco** [comment]
Thanks - I had a quick look and it seems fine - the only thing I spotted is that the `CMAKE_BUILD_TYPE` Release/Debug/etc should be made into a config option of the project (as opposed to a command line param), but since I haven't implemented that yet, it might as well stay like this until it gets done.

Does this fix the problem with `GITHUB_TOKEN` that you raised in #17 ? 

Do I take it that you are running this on a login node of a machine, that uses PBS and hence the need to remove the ssh? This is good because I will want to run it on the login node of daint/other too at some point (but using slurm) -  also running locally with no ssh and no slurm did work originally (just doing local builds), but I guess that's broken.

I'll test this branch on my existing daint builds for hpx/dca and if it all still works, I'll merge it.

**Comment by PDoakORNL** [comment]
Unfortunately the token puzzle remains.
Yes I'm running on a login node of the machine.
Still having trouble myself with the ctest_update command not bringing the code I expect into the build environment.  This clearly works correctly on the master version on daint.

Made my on cdash server so I can figure this out without constantly spamming the cscs server.

**Comment by PDoakORNL** [comment]
ok now I'm back testing on Cades-Condo Centos7 Cluster
#17 is now fixed as well

**Comment by PDoakORNL** [comment]
This is ready to merge after testing on your side.

**Comment by biddisco** [comment]
@PDoakORNL I've pushed a couple of fixes to the PR, but still got problems with my builds. I've added you as a collaborator (for some reason I thought that I couldn't push fixes to your banch, but it seems to have worked).

**Comment by PDoakORNL** [comment]
So just put in a fix for me hardcoding the spack load cmake command in. This couldn't have helped this PR work on other systems.

**Pull request merged**
